---
title: "Sklep_Rowerowy"
author: "Julia Sulka, Julia Urban, Barbara Michalska"
date: "2024-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_data}
library(readr)  # Do wczytywania CSV
library(naniar) # Do analizy brakujących danych

# Wczytanie danych
data <- read_csv("sklep_rowerowy.csv")

# Podgląd danych
head(data)

```

```{r missing_data}
# Liczba brakujących wartości w każdej kolumnie
library(naniar)
library(ggplot2)


n_miss(data)
  
# Wizualizacja brakujących danych
vis_miss(data, sort = TRUE, warn_large_data = FALSE, show_perc = TRUE) +
  labs(
    title = "Wizualizacja brakujących danych",
    subtitle = "Zawiera procent braków w poszczególnych kolumnach"
  ) +
  theme_minimal() + # Minimalny motyw dla lepszej czytelności
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  scale_fill_manual(
    values = c("#28B463","#FF5733"), # Kolor dla danych brakujących i obecnych
    name = "Status danych",          # Tytuł legendy
    labels = c("Obecne", "Brakujące") # Opis w legendzie
  )


gg_miss_upset(
  data, 
  nsets = 13, 
  main.bar.color = "Pink",      # Kolor głównego paska
  sets.bar.color = "Violet"       # Kolor pasków dla zestawów
)

ggplot(data = data, aes(x = Income, y = Age)) +
  geom_point(color = "grey70", size = 3) +      # Punkty dla kompletnych danych
  geom_miss_point(size = 3) +                  # Punkty dla braków
  scale_color_manual(
    values = c("darkorange", "cyan4"),         # Kolory dla obecnych i brakujących
    name = "Status danych",                    # Tytuł legendy
    labels = c("Obecne", "Brakujące")          # Etykiety w legendzie
  ) +
  theme_minimal() +
  facet_wrap(~ Region, scales = "free") +      # Grupowanie według Regionu
  labs(
    title = "Brakujące dane w relacji Income i Age",
    subtitle = "Podział na regiony",
    x = "Dochód",
    y = "Wiek"
  )




# Tworzenie wykresu z geom_miss_point
ggplot(data, aes(x = Income, y = Age)) +
  geom_miss_point() +
  labs(
    title = "Brakujące wartości w danych",
    subtitle = "Analiza powiązań braków pomiędzy Income i Age",
    x = "Dochód",
    y = "Wiek"
  ) +
  theme_minimal()

gg_miss_fct(data, fct = Gender)

gg_miss_fct(data, fct = Region)


gg_miss_fct(data, fct = Education)

```

```{r change_missing_data}

# Wypełnienie braków danych

library(dlookr)
library(VIM)

data_withoutNA <- hotdeck(data)   # Funkcja hotdeck uzupełnia braki danych

n_miss(data_withoutNA)            # Ponowne sprawdzenie czy w danych są braki

data_withoutNA <- hotdeck(data, imp_var = FALSE) #Poprawienie funkcji hotdeck

```

```{r}
#Ustawienie zasad dla poszczególnych zmiennych
library(editrules)
library(dplyr)
# Zmieniamy spacje w nagłówkach na kropki
colnames(data) <- gsub(" ", ".", colnames(data))
colnames(data_withoutNA) <- gsub(" ", ".", colnames(data_withoutNA))
colnames(data_withoutNA)


Rule <- editset(c(
  "ID > 0",
  "Marital.Status %in% c( 'Married', 'Single')",
  "Gender %in% c( 'Male', 'Female')",
  "Income > 0",
  "Children >= 0",
  "Education %in% c('Bachelors', 'Partial College', 'High School', 'Partial High School', 'Graduate Degree')",
  "Occupation %in% c('Skilled Manual', 'Clerical', 'Professional', 'Manual', 'Management')",
  "Home.Owner %in% c('Yes', 'No')",
  "Cars >= 0",
  "Commute.Distance %in% c('0-1 Miles', '1-2 Miles', '10+ Miles', '2-5 Miles', '5-10 Miles')",
  "Region %in% c('Europe', 'Pacific', 'North America')",
  "Age > 0",
  "Age <= 120",
  "Purchased.Bike %in% c('Yes', 'No')"
))
Rule

library(validate)

violations <- violatedEdits(Rule, data_withoutNA)
summary(violations)

library(knitr)

if (sum(violations) == 0) {
  kable(
    data.frame(Wynik = "Wszystkie reguły zostały spełnione. Brak błędów."),
    col.names = "Podsumowanie",
    align = "c"
  )
} else {
  print(summary(violations))
}
```

```{r}
#Czyszczenie nazw zmiennych
install.packages("janitor")
library(janitor)
zbior <- janitor::clean_names(data_withoutNA)
```

```{r}
#Utworzenie wykresu kolumnowego zależności między odległością od pracy, a zakupem roweru
library(ggplot2)
library(dplyr)
zbior$commute_distance <- factor(zbior$commute_distance, levels = c("0-1 Miles", "1-2 Miles", "2-5 Miles", "5-10 Miles", "10+ Miles"))
zbior$purchased_bike <- factor(zbior$purchased_bike, levels = c("Yes", "No"))
wykres_1 <- ggplot(zbior %>% filter(purchased_bike =="Yes"), aes(x=commute_distance, fill=purchased_bike)) +
   geom_bar(position = "dodge") +
   xlab("Odległość od pracy") +
   ylab("Liczba osób") + 
   labs(fill = "Zakup roweru") +
   ggtitle("Odległość od pracy, a zakup roweru") +
   scale_fill_manual(values = "#228b22") +
   theme_light()
 
install.packages("plotly", dependencies = TRUE)

library(plotly)

ggplotly(wykres_1)
 
 
```

```{r}
#Utworzenie wykresu zależności między płcią, typem zawodu, a zakupem roweru
library(ggplot2)
library(dplyr)
zbior$gender <- factor(zbior$gender, levels = c("Female", "Male"))
zbior$purchased_bike <- factor(zbior$purchased_bike, levels = c("Yes", "No"))

 wykres_2 <- ggplot(zbior %>% filter(purchased_bike =="Yes"), aes(x=occupation, fill=gender)) +
   geom_bar(position = "dodge") +
   xlab(" Typ zawodu") +
   ylab("Liczba osób") + 
   labs(fill = "Płeć") +
   ggtitle("Zakup roweru w zależności od typu zawodu z podziałem na płeć") +
   scale_fill_manual(values = c("Female" = "lightpink", "Male" = "lightblue")) +
   theme_gray()
 
 install.packages("plotly", dependencies = TRUE)
 library(plotly)
 ggplotly(wykres_2)
 

```

```{r}
#Utworzenie wykresu kołowego
zakup <- sum(zbior$purchased_bike == "Yes" &zbior $gender == "Female")
zakup
zakup_2 <- sum(zbior$purchased_bike == "Yes" & zbior$gender == "Male")
zakup_2
zakup_3 <- sum(zbior$purchased_bike == "Yes")
zakup_3
procent_kobiet <- (zakup/zakup_3) * 100
procent_kobiet
procent_mezczyzn <- (zakup_2/zakup_3) * 100
procent_mezczyzn
library(ggplot2)
dane_wykres_2 <- data.frame(
  Gender = c("Female", "Male"),
  numbers = c(50.10, 49.9)
)
  
wykres_3 <- ggplot(dane_wykres_2, aes (x="", y=numbers, fill=Gender)) +
  geom_bar(stat="identity", width = 1) +
  coord_polar("y", start = 0 ) +
   geom_text(aes(label = paste0(numbers, "%")), position = position_stack(vjust = 0.5)) +
  scale_fill_manual(values = c("Female" = "pink", "Male" = "lightblue")) +
  ggtitle("Zakup roweru w podziale na płeć") + 
  theme_light() +
  theme(
  plot.title = element_text(hjust = 0.5),
  axis.title.x = element_blank(),
  axis.title.y = element_blank()
  )
wykres_3

```


```{r}
#Utworzenie histogramu - zależność między wiekiem, a zakupem roweru
library(ggplot2)
library(dplyr)

wykres_4 <- ggplot(zbior, aes(age)) +
  geom_histogram(binwidth = 5, fill = "red", color = "black") +
  labs(title = "Zakup raweru w zależności do wieku", x = "Wiek", y = "Zakup roweru") +
  theme_minimal()

wykres_4

##Utworzenie wykresu słupkowego - zależność między regionem, a zakupem roweru
library(ggplot2)
library(dplyr)

wykres_5 <- ggplot(zbior, aes(region)) +
  geom_bar(fill = "pink", color = "lightgreen") +
  labs(title = "Zakup raweru w zależności do regionu zamieszkania", x = "Region", y = "Zakup roweru") +
  theme_minimal()

wykres_5

```


```{r}
#Utworzenie boxplota - zakup roweru względem zarobków
library(ggplot2)
library(dplyr)

wykres_6 <- ggplot(zbior, aes(x = purchased_bike, y = income)) +
    geom_boxplot(fill = "lightblue", color = "darkblue") +
  labs(title = "Zakup roweru z zleżności od zarobków", 
       x = "Zakup roweru", 
       y = "Zarobki") +
  theme_minimal()

wykres_6

#Utworzenie boxplota - zakup roweru względem zarobków z odstającymi wartościami

wykres_7 <- ggplot(zbior, aes(x = purchased_bike, y = income)) +
    geom_boxplot(outlier.color = "red", outlier.shape = 8) +
  labs(title = "Zakup roweru z zleżności od zarobków z odstającymi wartościami", 
       x = "Zakup roweru", 
       y = "Zarobki") +
  theme_minimal()

wykres_7

```



